### ISSUE TITLE
Header block error.

### ISSUE THREAD

**Issue by kakuzops** [ProofHub/api_v3#1]
Hi there
So when i try to integrate a page with the API i receive this error code "{code: 1201, message: "Incomplete headers"}", but i passing all headers are needed and i realy don't know how i recieve th error.
here my code example.
![carbon 1](https://user-images.githubusercontent.com/8216101/52001593-ecf28a80-24a6-11e9-9705-d688437c43d3.png)
(i changed the API-KEY just to send this issue).

thx for help

**Comment by ProofHub** [comment]
Hi Leonardo,

We will get this checked and will get back to you as soon as possible.

Thank you,

Ryan
ProofHub Team

*Download the mobile app!*

* <http://goog_1297878098/>*
* <https://goo.gl/ifs6jl>  <https://goo.gl/arNEF1>*

**Comment by ProofHub** [comment]
Hi Leonardo,

Could you please let us know are you sending this request for insert,
update or something else?

What method are you using with this request? All this information will help
us to assist you better.


Udit
ProofHub Team

*Download the mobile app*

<https://goo.gl/grkB6n>  <https://goo.gl/p8Emsd>

**Comment by kakuzops** [comment]
Hi proof,
so the method i'm using is POST to create a new "todo-list", the get method are ok but the post returns the error that i mentioned.

**Comment by ProofHub** [comment]
Hi Leonardo,

Could you please share the complete HTTPS POST request will all the
parameters you are sending? It will help us to find a quick fix.

Udit
ProofHub Team

*Download the mobile app*

<https://goo.gl/grkB6n>  <https://goo.gl/p8Emsd>

**Comment by kakuzops** [comment]
Hi, 
here the form's i call and send information
![carbon 2](https://user-images.githubusercontent.com/8216101/52124611-f4ce3e00-2610-11e9-9798-faa6aea97392.png)
![carbon 3](https://user-images.githubusercontent.com/8216101/52124610-f4ce3e00-2610-11e9-9459-b2a01658d4f7.png)

**Comment by ProofHub** [comment]
Hi Leonardo,

You are using the wrong URL to post the data.

It should be like: return http.post( 'project ID/todolist/TODOLIST
ID/*TASK*/TASK
ID' )

Also, please let us know what exactly are you posting on the task? Is it a
comment, a subtask or something else?

Please see all endpoints and documentation related to tasks here:
https://github.com/ProofHub/api_v3/blob/master/sections/tasks.md

Let me know if you have any questions.

Udit
ProofHub Team

*Download the mobile app*

<https://goo.gl/grkB6n>  <https://goo.gl/p8Emsd>

**Comment by kakuzops** [comment]
Hi , sorry for delay.

The ideia is create a TASK inside the todo-list, but same problem when i pass the parameters  i recieve the "Incomplete headers".

Again the method post.

![carbon 4](https://user-images.githubusercontent.com/8216101/52801102-51474980-3064-11e9-9d9e-7d14d253b966.png)

I think i missing a parameter, but i pass parameter iqual the api docs, https://github.com/ProofHub/api_v3/blob/master/sections/tasks.md#create-task

**Comment by ProofHub** [comment]
Hi Leonardo,

We will check this and will get back to you.

Thank you,

Ryan
ProofHub Team

*Download the mobile app!*

* <http://goog_1297878098/>*
* <https://goo.gl/ifs6jl>  <https://goo.gl/arNEF1>*

**Comment by ProofHub** [comment]
Hi Leonardo,

Thanks for writing in.

Please share with us the entire code that you've written to create a task
inside a task list. It will enable the concerned team to look closely.
-- 
Adi

ProofHub Team

*Download the mobile app*

* <http://goog_1297878098/>*
* <https://goo.gl/ifs6jl>  <https://goo.gl/arNEF1>*

**Comment by kakuzops** [comment]
Here the code in gist, in the code i changed key to - for privacity.
https://gist.github.com/kakuzops/53015ea3cb5e5316d8a5b0e523c25303

thx for supporting.

**Comment by ProofHub** [comment]
Hi Leonardo,

The concerned team looked into your code and found an error in your post
request. In it you've written "post('2301042557/todolist/68486313569/tasks')".
In it you've mentioned "todolist" which is incorrect as it should be
"todolists". Please make this change and try again. For further reference
please check
https://github.com/ProofHub/api_v3/blob/master/sections/tasks.md#create-task
.
-- 
Adi

ProofHub Team

*Download the mobile app*

* <http://goog_1297878098/>*
* <https://goo.gl/ifs6jl>  <https://goo.gl/arNEF1>*

**Comment by kakuzops** [comment]
The post methods chaged but the same error, i recieve code :1201 and Incomplete headers i think is missing something but i passe the same iqual in docs

**Comment by kakuzops** [comment]
In the headers i recieved the Status code 200, but the same error code 1201

**Comment by ProofHub** [comment]
Hi Leonardo,

Could you please share your POST requests and the parameters you are
sending along with it?

This will help us to assist you better.

Udit
ProofHub Team

*Download the mobile app*

<https://goo.gl/grkB6n>  <https://goo.gl/p8Emsd>

**Comment by kakuzops** [comment]
Hello, in the gist has the comand i send, var task {} is the params

**Comment by ProofHub** [comment]
Hi Leonardo,

1. Please correct 'todolist' to '*todolists*'.
2. The Error Code '1201' is sent when 'content type' header is incorrect.
3. Below is the sample code we tested based on your inputs and it's working
fine. You can adapt your code to match.

=====================
<html>
<head>

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
const http = axios.create({
    baseURL: 'https://apis3.proofhub.com/api/v3/projects/',
    headers: {
     'X-API-KEY': '-',
     'Content-Type': 'application/json ',
     'User-Agent': 'Apis3 (leonardo.nogueira@apis3.com)'
    }
});

 //XXXXXXXX- project id
//YYYYYYYYY- list id
http.post('XXXXXXXX/todolists/YYYYYYYY/tasks',
{
    "title": "Get it signed",
    "description": "Need to get it signed off immediately",
   }
)
    .then(function (response) {
     console.log(response);
}
)
  .catch(function (error) {
    console.log(error);
}
);
</script>
</head>
<body></body>
</html>


=====================

Let us know if you face any other error code and we'd love to help. :)

Udit
ProofHub Team

*Download the mobile app*

<https://goo.gl/grkB6n>  <https://goo.gl/p8Emsd>

**Comment by kakuzops** [comment]
Hi, sorry for the delay in the response.
Everything is fine and working well.
Thanks for the support and help.
