### ISSUE TITLE
Get a project's email-in address

### ISSUE THREAD

**Issue by MaybeThisIsRu** [ProofHub/api_v3#10]
In the [get project details](https://github.com/ProofHub/api_v3/blob/master/sections/projects.md#get-project) call, could its email-in address be added please?

**Comment by ProofHub** [comment]
Hi, 
Email-In addresses are for task lists, as each email-in will create a task in that specific tasklist. This is already included in the gettodolist API response. There are no separate email-in addresses at Project level. Do write to us at support@proofhub.com in case you have any doubts.

Regards,
Team ProofHub
