### ISSUE TITLE
OAuth 2.0 integration 

### ISSUE THREAD

**Issue by MaybeThisIsRu** [ProofHub/api_v3#12]
ProofHub's UI/UX is very overwhelming for some of our users. They need something much more simplistic. Is there a possibility of adding an API endpoint that can login a user given their email and their hashed password?

**Comment by ProofHub** [comment]
Hi, Each user has an API key that can be used to trigger APIs to ProofHub. The API belongs to the user so all actions done via the API are attributed to that user in ProofHub records. This API key can be found in the user's profile information and set once for each user you want to call the APIs for. Unfortunately, it cannot be retrieved via an API call.
Apart from this, we are happy to provide an onboarding/product walkthrough for new users in your account to make them comfortable about getting started with ProofHub quickly. Do connect with us at support@proofhub.com to discuss onboarding as well as other training sessions that we offer.
