### ISSUE TITLE
Filters for endpoints

### ISSUE THREAD

**Issue by bryangruneberg** [ProofHub/api_v3#3]
There seems to be no way to query the api for tasks, projects, lists, etc which match criteria. For my usecase, it would be necessary to query the API for all tasks which are assigned to me, of for all tasks with a title which contains a certain string. Another requirement would be to search all projects in a specific status, or set to a specific color.

**Comment by ProofHub** [comment]
-- Please reply above this line --


            Hi,

Thanks for writing in. All the required queries are available at the
GitHub link. However, considering your request, kindly find my
responses below :

API query for all tasks for the concerned user :
https://companyURL.proofhub.com/api/v3/alltodo?projects=&labels=&due=today&completed=false&include_unassigned=false&include_subtasks=false&assigned=userid&work_on=true&page=1&start=0&limit=100
[1]

API query for the project :
https://companyURL.proofhub.com/api/v3/projects?limit=100&categories=&color=&status=statusid&colors=colorCodes&assigned=&sort_by=category&page=1&start=0
[2]

API query for the title which contains a certain string is not
available. 

Do let us know for any further query.

Links:
------
[1]
https://vinay31.proofhub.com/api/v3/alltodo?projects=&labels=&due=today&completed=false&include_unassigned=false&include_subtasks=false&assigned=3260499912&work_on=true&page=1&start=0&limit=100
[2]
https://vinay31.proofhub.com/api/v3/projects?limit=100&categories=&color=&status=828714938&colors=009385%2C2192E8&assigned=&sort_by=category&page=1&start=0

--
Ryan
support@proofhub.com

**Comment by bryangruneberg** [comment]
ahhh - I didn't realize it was possible to filter that queries! Thanks for the help and reply
