### ISSUE TITLE
How best way to get all tasks?

### ISSUE THREAD

**Issue by jbsolucoes** [ProofHub/api_v3#6]
Hi! I need get all tasks, to integration with BI application, but the format to get data is realy slow, we above 2k (few months) of tasks, but, because your rate limits, to get projects, lists and tasks we need many and many requests.
Any solution to minimize this slow?
Thank you!

**Comment by ProofHub** [comment]
Hi, 

Thanks for contacting. 
You can get all the tasks in a tasklist with a single command. Have a look at [get-all-tasks API](https://github.com/ProofHub/api_v3/blob/master/sections/tasks.md#get-all-tasks). You can go through the API help to get information about all the [available APIs here](https://github.com/ProofHub/api_v3#api-endpoints).

**Comment by jbsolucoes** [comment]
Hi, thanks for reply, but this is a problem, we have hundreds of projects with hundreds of tasklists, with your rate limit we need about one hour to get all tasks... this is the problem.
I discover comand alltodo in api (api/v3/alltodo, without documentation), if we can have something like that for all tasks, or increase rate limit...

Thanks

**Comment by ProofHub** [comment]
Hi,

Please check the API to get list of all tasks for all projects [here ](https://github.com/ProofHub/api_v3/blob/master/sections/everything.md). It will help in your scenario.
