### ISSUE TITLE
Not able to create a task

### ISSUE THREAD

**Issue by Nathandsn** [ProofHub/api_v3#9]
When sending a post request to create a task I'm receiving the following answer:

![image](https://user-images.githubusercontent.com/32044092/176062439-89cea242-7fe9-4156-b1f2-325e375a1c77.png)

I didn't find in the docs neither the "code" nor the "message" referring to this. Here is a snippet of my python dict structure, where 'task' is being replaced by a string.

![image](https://user-images.githubusercontent.com/32044092/176062638-e38c6385-3d74-4221-97f8-89fb80a3d119.png)

**Comment by ProofHub** [comment]
Hi Nathan,
This issue can occur if the mandatory field "title" is missing. Can you share the logs of the request and response directly to support@proofhub.com alongwith your ProofHub account details to help investigate further.
